# Generated by Django 2.0.7 on 2018-07-23 07:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('message', '0003_message_created_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reader',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cc', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='CC', to=settings.AUTH_USER_MODEL)),
                ('message', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='message.Message')),
            ],
        ),
        migrations.AlterModelOptions(
            name='reply',
            options={'ordering': ['created_at']},
        ),
    ]
