# Generated by Django 2.0.7 on 2018-07-23 07:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('message', '0004_auto_20180723_0723'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reader',
            name='cc',
        ),
        migrations.RemoveField(
            model_name='reader',
            name='message',
        ),
        migrations.DeleteModel(
            name='Reader',
        ),
    ]
